### PR TITLE
Install dependencies automatically / Basic UI

### PR DESCRIPTION
**Pull request by dunkeyyfong**
I update simple UI for TrollRestore. It when run app, connected device, enter app and run
image

### CODE REVIEW

**Comment by verygenericname** [comment]
By removing the breaking hard link part, you cause a bootloop. Also the tool is pretty simple as is, you just double click it and enter the apps name lol

**Comment by dunkeyyfong** [comment]
Oh, I think it's okay :v. I'll update it

**Comment by seregonwar** [comment]
if you want to use the version with gui you can use my fork, the app is tested and does not cause bootloop since breaking hard link part is present, you can also scroll through the system apps (and not) since I inserted a drop-down menu, the code is testable also on ios 18 but obviously trollhelper will not install. I leave you my repo here: https://github.com/seregonwar/TrollRestore-GuiVersion

**Comment by Abdullah963go** [comment]
Fghe

**Review by Abdullah963go — APPROVED** [review]

**Review by Abdullah963go — APPROVED** [review]

**Review by Ujackslot — APPROVED** [review]

**Comment by JJTech0130** [comment]
I'm a bit confused at the purpose of this PR; it seems to have some UI stuff but was that removed?

**Comment by JJTech0130** [comment]
In any case I don't think shelling out to pip is the correct approach

**Pull request closed without merging**
